<a href="https://colab.research.google.com/github/umesh2908/Machine-learning-projects/blob/master/Camelot_PDFfile_table_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import camelot

In [ ]:
tables=camelot.read_pdf('Nov.pdf', flavor='lattice', pages='5')

In [ ]:
type(Tables)

camelot.core.TableList

In [ ]:
for table in tables:
    print(table.df)

           0                          1                       2  \
0      Dates  Scheduled \nDrawal in Mus  Actual drawal in \nMus
1        (1)                        (2)                     (3)
2  26-Nov-18                  19.285163               19.859587
3  27-Nov-18                  20.106608               20.468143
4  28-Nov-18                  19.877834               20.431598
5  29-Nov-18                  20.181343               20.521232
6  30-Nov-18                  20.343988               20.920619
7   1-Dec-18                  18.257288               18.505435
8   2-Dec-18                  18.143513               18.271036
9      Total                 136.195737              138.977650

                    3                            4  \
0  Deviation in \nMus  Deviation Amount in \nLakhs
1         (4)=(3)-(2)                          (5)
2             0.57442                     13.08605
3             0.36154                      9.43118
4             0.55376                     11.93315
5             0.33989                     11.11210
6             0.57663                     17.94033
7             0.24815                      6.99263
8             0.12752                      3.08458
9             2.78191                     73.58001

                                  5                         6
0  ADDI Deviation \nAmount in Lakhs  NET Deviation \nin Lakhs
1                               (6)               (7)=(5)+(6)
2                           0.41609                  13.50214
3                           0.07128                   9.50246
4                           0.49559                  12.42874
5                           0.03481                  11.14691
6                           0.17655                  18.11688
7                           0.31445                   7.30708
8                           0.00000                   3.08458
9                           1.50878                  75.08879
                    0                          1                       2  \
0               Dates  Scheduled \nDrawal in Mus  Actual drawal in \nMus
1                 (1)                        (2)                     (3)
2           26-Nov-18                  24.540364               24.220883
3           27-Nov-18                  24.608658               24.548619
4           28-Nov-18                  24.998963               24.707874
5           29-Nov-18                  24.624693               24.427962
6           30-Nov-18                  25.304455               24.853394
7            1-Dec-18                  24.711376               24.157126
8  2-Dec-18\n2-Dec-18       23.312872\n23.312872    22.694881\n22.694881
9               Total                 172.101382              169.610739

                    3                            4  \
0  Deviation in \nMus  Deviation Amount in \nLakhs
1         (4)=(3)-(2)                          (5)
2            -0.31948                     -3.17506
3            -0.06004                      3.53621
4            -0.29109                     -4.00577
5            -0.19673                     -3.04175
6            -0.45106                    -10.80138
7            -0.55425                    -11.45458
8  -0.61799\n-0.61799           -9.92555\n-9.92555
9            -2.49064                    -38.86788

                                  5                         6
0  ADDI Deviation \nAmount in Lakhs  NET Deviation \nin Lakhs
1                               (6)               (7)=(5)+(6)
2                           0.00735                  -3.16771
3                           0.87841                   4.41463
4                           0.02668                  -3.97910
5                           0.31920                  -2.72255
6                           0.00822                 -10.79315
7                           0.00000                 -11.45458
8                  0.00000\n0.00000        -9.92555\n-9.92555
9                           1.23987                 -37.62801
           0                          1                       2  \
0      Dates  Scheduled \nDrawal in Mus  Actual drawal in \nMus
1        (1)                        (2)                     (3)
2  26-Nov-18                  12.495039               12.926605
3  27-Nov-18                  12.429976               12.946159
4  28-Nov-18                  13.015741               13.602186
5  29-Nov-18                  13.303010               13.543871
6  30-Nov-18                  13.232617               13.772221
7   1-Dec-18                  12.945092               13.380257
8   2-Dec-18                  12.157603               12.573734
9      Total                  89.579078               92.745033

                    3                            4  \
0  Deviation in \nMus  Deviation Amount in \nLakhs
1         (4)=(3)-(2)                          (5)
2             0.43157                      8.87354
3             0.51618                     13.95967
4             0.58645                     12.32153
5             0.24086                      8.24432
6             0.53960                     15.84182
7             0.43516                     10.47195
8             0.41613                      7.60933
9             3.16596                     77.32217

                                  5                         6
0  ADDI Deviation \nAmount in Lakhs  NET Deviation \nin Lakhs
1                               (6)               (7)=(5)+(6)
2                           0.15029                   9.02383
3                           0.66732                  14.62699
4                           2.47873                  14.80026
5                           0.02965                   8.27397
6                           0.12295                  15.96478
7                           0.21551                  10.68747
8                           0.07466                   7.68399
9                           3.73912                  81.06128
           0                          1                       2  \
0      Dates  Scheduled \nDrawal in Mus  Actual drawal in \nMus
1        (1)                        (2)                     (3)
2  26-Nov-18                   2.844386                2.812712
3  27-Nov-18                   2.844914                2.846186
4  28-Nov-18                   2.757875                2.873379
5  29-Nov-18                   2.701287                2.847750
6  30-Nov-18                   2.559150                2.850747
7   1-Dec-18                   2.317802                2.557462
8   2-Dec-18                   2.164327                2.328161
9      Total                  18.189739               19.116397

                    3                            4  \
0  Deviation in \nMus  Deviation Amount in \nLakhs
1         (4)=(3)-(2)                          (5)
2            -0.03167                     -0.66385
3             0.00127                      0.19184
4             0.11550                      2.38065
5             0.14646                      4.48529
6             0.29160                      8.84039
7             0.23966                      5.88493
8             0.16383                      3.05642
9             0.92666                     24.17567

                                  5                         6
0  ADDI Deviation \nAmount in Lakhs  NET Deviation \nin Lakhs
1                               (6)               (7)=(5)+(6)
2                           0.00000                  -0.66385
3                           0.00000                   0.19184
4                           0.00000                   2.38065
5                           0.00000                   4.48529
6                           0.00000                   8.84039
7                           0.00000                   5.88493
8                           0.00000                   3.05642
9                           0.00000                  24.17567
           0                          1                       2  \
0      Dates  Scheduled \nDrawal in Mus  Actual drawal in \nMus
1        (1)                        (2)                     (3)
2  26-Nov-18                   0.471110                0.481473
3  27-Nov-18                   0.484857                0.486587
4  28-Nov-18                   0.472822                0.489303
5  29-Nov-18                   0.470096                0.489504
6  30-Nov-18                   0.498090                0.494753
7   1-Dec-18                   0.487109                0.466864
8   2-Dec-18                   0.467036                0.459765
9      Total                   3.351120                3.368249

                    3                            4  \
0  Deviation in \nMus  Deviation Amount in \nLakhs
1         (4)=(3)-(2)                          (5)
2             0.01036                      0.85397
3             0.00173                      0.14255
4             0.01648                      1.35812
5             0.01941                      1.59928
6            -0.00334                     -0.27496
7            -0.02024                     -1.66826
8            -0.00727                     -0.59919
9             0.01713                      1.41152

                                  5                         6
0  ADDI Deviation \nAmount in Lakhs  NET Deviation \nin Lakhs
1                               (6)               (7)=(5)+(6)
2                           3.85751                   4.71148
3                           2.94620                   3.08876
4                           3.29543                   4.65355
5                           3.35938                   4.95866
6                           1.73476                   1.45981
7                           0.60649                  -1.06177
8                           1.61033                   1.01114
9                          17.41010                  18.82163

In [ ]:
tables.n

5

In [ ]:
tables[4].parsing_report

{'accuracy': 99.99, 'whitespace': 0.0, 'order': 5, 'page': 5}

In [ ]:
NDMC_temp=tables[3].df
NDMC_2=tables[4].df
NDMC_temp

,0,1,2,3,4,5,6
0,Dates,Scheduled \nDrawal in Mus,Actual drawal in \nMus,Deviation in \nMus,Deviation Amount in \nLakhs,ADDI Deviation \nAmount in Lakhs,NET Deviation \nin Lakhs
1,(1),(2),(3),(4)=(3)-(2),(5),(6),(7)=(5)+(6)
2,26-Nov-18,2.844386,2.812712,-0.03167,-0.66385,0.00000,-0.66385
3,27-Nov-18,2.844914,2.846186,0.00127,0.19184,0.00000,0.19184
4,28-Nov-18,2.757875,2.873379,0.11550,2.38065,0.00000,2.38065
5,29-Nov-18,2.701287,2.847750,0.14646,4.48529,0.00000,4.48529
6,30-Nov-18,2.559150,2.850747,0.29160,8.84039,0.00000,8.84039
7,1-Dec-18,2.317802,2.557462,0.23966,5.88493,0.00000,5.88493
8,2-Dec-18,2.164327,2.328161,0.16383,3.05642,0.00000,3.05642
9,Total,18.189739,19.116397,0.92666,24.17567,0.00000,24.17567

In [ ]:
NDMC=NDMC_temp.rename(columns=NDMC_temp.iloc[0]).drop(NDMC_temp.index[0])
NDMC_2=NDMC_2.rename(columns=NDMC_2.iloc[0]).drop(NDMC_2.index[0])
NDMC

,Dates,Scheduled \nDrawal in Mus,Actual drawal in \nMus,Deviation in \nMus,Deviation Amount in \nLakhs,ADDI Deviation \nAmount in Lakhs,NET Deviation \nin Lakhs
1,(1),(2),(3),(4)=(3)-(2),(5),(6),(7)=(5)+(6)
2,26-Nov-18,2.844386,2.812712,-0.03167,-0.66385,0.00000,-0.66385
3,27-Nov-18,2.844914,2.846186,0.00127,0.19184,0.00000,0.19184
4,28-Nov-18,2.757875,2.873379,0.11550,2.38065,0.00000,2.38065
5,29-Nov-18,2.701287,2.847750,0.14646,4.48529,0.00000,4.48529
6,30-Nov-18,2.559150,2.850747,0.29160,8.84039,0.00000,8.84039
7,1-Dec-18,2.317802,2.557462,0.23966,5.88493,0.00000,5.88493
8,2-Dec-18,2.164327,2.328161,0.16383,3.05642,0.00000,3.05642
9,Total,18.189739,19.116397,0.92666,24.17567,0.00000,24.17567

In [ ]:
NDMC_new=NDMC.drop(NDMC.index[0])
NDMC_2=NDMC_2.drop(NDMC_2.index[0])

In [ ]:
NDMC_new

,Dates,Scheduled \nDrawal in Mus,Actual drawal in \nMus,Deviation in \nMus,Deviation Amount in \nLakhs,ADDI Deviation \nAmount in Lakhs,NET Deviation \nin Lakhs
2,26-Nov-18,2.844386,2.812712,-0.03167,-0.66385,0.00000,-0.66385
3,27-Nov-18,2.844914,2.846186,0.00127,0.19184,0.00000,0.19184
4,28-Nov-18,2.757875,2.873379,0.11550,2.38065,0.00000,2.38065
5,29-Nov-18,2.701287,2.847750,0.14646,4.48529,0.00000,4.48529
6,30-Nov-18,2.559150,2.850747,0.29160,8.84039,0.00000,8.84039
7,1-Dec-18,2.317802,2.557462,0.23966,5.88493,0.00000,5.88493
8,2-Dec-18,2.164327,2.328161,0.16383,3.05642,0.00000,3.05642
9,Total,18.189739,19.116397,0.92666,24.17567,0.00000,24.17567

In [ ]:
NDMC_2

,Dates,Scheduled \nDrawal in Mus,Actual drawal in \nMus,Deviation in \nMus,Deviation Amount in \nLakhs,ADDI Deviation \nAmount in Lakhs,NET Deviation \nin Lakhs
2,26-Nov-18,0.471110,0.481473,0.01036,0.85397,3.85751,4.71148
3,27-Nov-18,0.484857,0.486587,0.00173,0.14255,2.94620,3.08876
4,28-Nov-18,0.472822,0.489303,0.01648,1.35812,3.29543,4.65355
5,29-Nov-18,0.470096,0.489504,0.01941,1.59928,3.35938,4.95866
6,30-Nov-18,0.498090,0.494753,-0.00334,-0.27496,1.73476,1.45981
7,1-Dec-18,0.487109,0.466864,-0.02024,-1.66826,0.60649,-1.06177
8,2-Dec-18,0.467036,0.459765,-0.00727,-0.59919,1.61033,1.01114
9,Total,3.351120,3.368249,0.01713,1.41152,17.41010,18.82163

In [ ]:
Table_1=pd.concat([NDMC_new, NDMC_2])
Table_1.to_excel("NDMC.xlsx")